# Generated by Django 2.1.7 on 2019-03-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.Books', verbose_name='书籍ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='是否违规'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.Passport', verbose_name='用户ID'),
        ),
    ]
