# Generated by Django 2.1.7 on 2019-03-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(db_column='is_delete', default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='create_time', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='update_time', verbose_name='更新时间')),
                ('type_id', models.SmallIntegerField(choices=[(0, '编程'), (1, '互联网'), (2, 'web'), (3, '交互设计'), (4, '经济'), (5, '算法')], db_column='type', default=0, verbose_name='类别')),
                ('name', models.CharField(db_column='name', max_length=80, verbose_name='书名')),
                ('desc', models.CharField(db_column='description', max_length=140, verbose_name='简介')),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=10, verbose_name='价格')),
                ('stock', models.IntegerField(db_column='stock', default=500, verbose_name='库存')),
                ('sales', models.IntegerField(db_column='sales', default=0, verbose_name='销量')),
                ('detail', models.CharField(db_column='detail', max_length=400, verbose_name='详情')),
                ('image', models.CharField(db_column='image', max_length=140, verbose_name='图片地址')),
                ('status', models.SmallIntegerField(choices=[(0, '库存充足'), (1, '库存不足'), (2, '没有库存'), (3, '补货中')], db_column='status', default=0, verbose_name='状态')),
                ('discount', models.FloatField(db_column='discount', default=1.0, verbose_name='折扣')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'db_table': 'books',
            },
        ),
    ]
